# Frontend Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: dev
  labels:
    app: web-app
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      location / {
        return 200 "Hello from Frontend Application!\n";
      }

      location /api/ {
        proxy_pass http://backend-svc.dev.svc.cluster.local/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      location /health {
        return 200 'OK';
      }
    }

---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: dev
  labels:
    app: web-app

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.28-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: frontend-port
          containerPort: 80

        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf

        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

        livenessProbe:
          httpGet:
            path: /health
            port: frontend-port
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: frontend-port
          initialDelaySeconds: 5
          periodSeconds: 10

      volumes:
      - name: nginx-config
        configMap:
          name: frontend-config

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: dev
  labels:
    app: web-app
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - name: http
    port: 80
    targetPort: frontend-port
    nodePort: 30080
    protocol: TCP